### PR TITLE
Add github actions build

### PR DESCRIPTION
**Pull request by mdavidsaver**
A quick attempt to enable build tests for #29.  Perhaps of less immediate usefulness as that issue has progressed to runtime testing (not currently possible for osx/arm64 with GHA).  Maybe useful wrt. #28 (or maybe not).

Moves the unittests into the installed tree, where they can be more easily run by users.  imo. this is good practice.

Currently skips some tests when the softIoc executable is missing.  This build uses `epicscorelibs`, so the ~equivalent `epicscorelibs.ioc` could be used instead.

```sh
python -m epicscorelibs.ioc -m "P=XYZ" -d path/to/soft_records.db
```

cf. https://github.com/mdavidsaver/epicscorelibs/blob/8817bb24d4e83345288fa3ad6b40e6027d9e7c7a/src/python/epicscorelibs/test/test_ioc_ca.py#L50-L53

### CODE REVIEW

**Comment by Araneidae** [comment]
Is it necessary to move the tests into a submodule of cothread?  Doing this makes the tests part of the standard install, which doesn't seem right to me; we definitely don't do this for [pythonIoc](https://github.com/dls-controls/pythonSoftIOC).

**Comment by mdavidsaver** [comment]
No, not necessary.

I've been doing this for [my](https://github.com/mdavidsaver/p4p/tree/master/src/p4p/test) python packages for some time.  (I can't now recall where I picked up the habit)  I routinely ask a user reporting a problem to run the tests.  Usually this just rules out some possibilities right away.  Occasionally, it has turned up an interesting failure.

Out of curiosity, a quick check finds that 49 of ~250 python packages install (with Debian) on my laptop include unittests.  So fairly common, but certainly not universal.  This includes some big names like numpy/scipy, so I feel I'm in good company.

```
$ cd /usr/lib/python3/dist-packages
$ find . -name 'test_*.py'| cut -d '/' -f '-2'|sort -u|wc -l
49
```

**Comment by Araneidae** [comment]
I'll ask @thomascobb for an opinion, if he will!

**Comment by AlexanderWells-diamond** [comment]
This is no longer required, we have added Github actions to build (and test) cothread on a variety of platforms and Python versions. This was done in #41.

**Pull request closed without merging**
