### PR TITLE
Create catalog-info.yaml

### PR DESCRIPTION
**Pull request by stan-dot**

### CODE REVIEW

**Comment by Araneidae** [comment]
What is the purpose of this file, and which tools are expected to consume this data?  The commit message should probably answer this question.

**Comment by gilesknap** [comment]
@stan-dot I've discussed this with @Araneidae in person.

@AlexanderWells-diamond please could you review/merge this PR - thanks!

**Comment by Araneidae** [comment]
I would still like to see the commit message amended to explain the purpose of this commit.

**Review by AlexanderWells-diamond — CHANGES_REQUESTED** [review]
Could you please add a slightly more descriptive commit message, referencing the Dev Portal. May as well rewrite the existing commit to do that.

**Review by AlexanderWells-diamond — APPROVED** [review]
Looks fine to me. Please do a squash merge - no point keeping both commits.

**Comment by stan-dot** [comment]
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

I get this message @AlexanderWells-diamond  I think you should be able to see a one-button squash-and-merge option

**Pull request merged**
